### ISSUE TITLE
Failed to read from csv

### ISSUE THREAD

**Issue by mez-0** [byt3bl33d3r/SprayingToolkit#20]
`atomizer` fails to read from  `--csvfile`. 

### CSV File 
```
email,password
test.email@abc.com,Password1
abc.email@abc.com,Password2
def.email@abc.com,Password3
```

### atomizer error

```
pentest/osint/SprayingToolkit/atomizer.py owa test.com --csvfile test-creds.csv --user-row-name email --pass-row-name password
[*] Trying to find autodiscover URL
[+] Using OWA autodiscover URL: None
[*] OWA domain appears to be hosted on Office365
[*] Using Office 365 autodiscover URL: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
[-] Error parsing internal domain name using OWA. This usually means OWA is being hosted on-prem or the target has a hybrid AD deployment
    Do some recon and pass the custom OWA URL as the target if you really want the internal domain name, password spraying can still continue though :)

    Full error: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

[*] Starting spray at 2019-11-14 10:57:43 UTC
Traceback (most recent call last):
  File "/pentest/osint/SprayingToolkit/atomizer.py", line 222, in <module>
    pass_row_name=args['--pass-row-name']
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/pentest/osint/SprayingToolkit/atomizer.py", line 113, in atomize_csv
    for row in csvreader
  File "/pentest/osint/SprayingToolkit/atomizer.py", line 113, in <listcomp>
    for row in csvreader
KeyError: 'email'
```

Granted, these emails are all fake; but it should at least try to request them? I have also tried setting the column names to `Email Address` and `Password`. To no avail.

I am also running version `1.0.0dev`.

**Comment by mez-0** [comment]
Removal of whitepace in csv headers fixed the issue.
