### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by i-am-internet** [byt3bl33d3r/SprayingToolkit#3]
Just trying this for the first time and I'm getting this error:
```
python3 atomizer.py owa domain.com Password1 --userfile users.txt --debug
MainThread urllib3.connectionpool: Starting new HTTPS connection (1): autodiscover.domain.com:443
MainThread urllib3.connectionpool: Starting new HTTP connection (1): autodiscover.domain.com:80
MainThread urllib3.connectionpool: http://autodiscover.domain.com:80 "GET /autodiscover/autodiscover.xml HTTP/1.1" 302 0
MainThread urllib3.connectionpool: Starting new HTTPS connection (1): autodiscover-s.outlook.com:443
MainThread urllib3.connectionpool: https://autodiscover-s.outlook.com:443 "GET /autodiscover/autodiscover.xml HTTP/1.1" 401 0
MainThread         owasprayer: [+] Using OWA autodiscover URL: http://autodiscover.domain.com/autodiscover/autodiscover.xml
MainThread urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
MainThread urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /domain.com/.well-known/openid-configuration HTTP/1.1" 200 1575
MainThread         owasprayer: [*] OWA domain appears to be hosted on Office365
MainThread urllib3.connectionpool: Starting new HTTP connection (1): autodiscover.domain.com:80
MainThread urllib3.connectionpool: http://autodiscover.domain.com:80 "POST /autodiscover/autodiscover.xml HTTP/1.1" 302 0
MainThread urllib3.connectionpool: Starting new HTTPS connection (1): autodiscover-s.outlook.com:443
MainThread urllib3.connectionpool: https://autodiscover-s.outlook.com:443 "GET /autodiscover/autodiscover.xml HTTP/1.1" 401 0
Traceback (most recent call last):
  File "/root/scripts/SprayingToolkit/core/utils/ntlmdecoder.py", line 219, in ntlmdecode
    st = base64.b64decode(st_raw)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "atomizer.py", line 101, in <module>
    atomizer.owa()
  File "atomizer.py", line 64, in owa
    password=self.password,
  File "/root/scripts/SprayingToolkit/core/sprayers/owa.py", line 19, in __init__
    self.recon()
  File "/root/scripts/SprayingToolkit/core/sprayers/owa.py", line 36, in recon
    self.netbios_domain = self.get_owa_domain(self.autodiscover_url)
  File "/root/scripts/SprayingToolkit/core/sprayers/owa.py", line 56, in get_owa_domain
    ntlm_info = ntlmdecode(r.headers["WWW-Authenticate"])
  File "/root/scripts/SprayingToolkit/core/utils/ntlmdecoder.py", line 221, in ntlmdecode
    raise Exception(f"Input is not a valid base64-encoded string: {e}")
Exception: Input is not a valid base64-encoded string: Incorrect padding
```

**Comment by i-am-internet** [comment]
Might not be of any use though, was doing some semi-manual testing against https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml and it appears to be randomly providing the xml file when you provide invalid creds. Hope I'm wrong but FYI regardless.
